<?php

namespace AppBundle\Repository;

/**
 * TransToLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllSort($sort)
    {
        return $this->findBy(array(), array('id' => $sort));
    }

    public function findWithSearch($domain, $code)
    {
        return $this
            ->createQueryBuilder('t')
            ->where('t.domain = :domain')
            ->andWhere("t.code LIKE :code")
            ->setParameter('domain', $domain)
            ->setParameter('code', '%'.$code.'%')
            ->getQuery()
            ->getResult()
            ;
    }

}
