<?php

namespace AppBundle\Repository;

/**
 * TransToLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransToLangRepository extends \Doctrine\ORM\EntityRepository
{

    public function findWithDomain($domain, $lang)
    {
        return $this
            ->createQueryBuilder('t')
            ->leftJoin('t.translation', 'trans')
            ->where('trans.domain = :domain')
            ->andWhere("t.lang = :lang")
            ->setParameter('domain', $domain)
            ->setParameter('lang', $lang)
            ->getQuery()
            ->getResult()
            ;
    }
}
