# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
    app.normalizer.not_found_exception:
        class: ApiBundle\Normalizer\NotFoundHttpExceptionNormalizer
        arguments:
            - { type: 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' }
        tags:
            - { name: app.normalizer }
    app.normalizer.resource_validation_exception:
        class: ApiBundle\Normalizer\ResourceValidationExceptionNormalizer
        arguments:
            - { type: 'AppBundle\Exception\ResourceValidationException' }
        tags:
            - { name: app.normalizer }
    app.normalizer.personalized_exception:
        class: ApiBundle\Normalizer\PersonalizedExceptionNormalizer
        arguments:
            - { type: 'AppBundle\Exception\PersonalizedException' }
        tags:
            - { name: app.normalizer }
    app.exception_subscriber:
        class: ApiBundle\EventSubscriber\ExceptionListener
        arguments:
            - '@jms_serializer'
        tags:
            - { name: kernel.event_subscriber }

#            Symfony\Component\HttpKernel\Exception\NotFoundHttpException