<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTjdexrf\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTjdexrf/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTjdexrf.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTjdexrf\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerTjdexrf\appProdDebugProjectContainer(array(
    'container.build_hash' => 'Tjdexrf',
    'container.build_id' => 'b04e06d3',
    'container.build_time' => 1523005877,
));
