<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJzhdt1p\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJzhdt1p/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJzhdt1p.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJzhdt1p\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJzhdt1p\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Jzhdt1p',
    'container.build_id' => 'c0891cd2',
    'container.build_time' => 1523005404,
));
