<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.exception_subscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/ApiBundle/Normalizer/NormalizerInterface.php';
include_once $this->targetDirs[3].'/src/ApiBundle/Normalizer/AbstractNormalizer.php';
include_once $this->targetDirs[3].'/src/ApiBundle/Normalizer/NotFoundHttpExceptionNormalizer.php';
include_once $this->targetDirs[3].'/src/ApiBundle/Normalizer/ResourceValidationExceptionNormalizer.php';
include_once $this->targetDirs[3].'/src/ApiBundle/Normalizer/PersonalizedExceptionNormalizer.php';
include_once $this->targetDirs[3].'/src/ApiBundle/EventSubscriber/ExceptionListener.php';

$this->services['app.exception_subscriber'] = $instance = new \ApiBundle\EventSubscriber\ExceptionListener(${($_ = isset($this->services['jms_serializer']) ? $this->services['jms_serializer'] : $this->getJmsSerializerService()) && false ?: '_'});

$instance->addNormalizer(new \ApiBundle\Normalizer\NotFoundHttpExceptionNormalizer(array('type' => 'Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException')));
$instance->addNormalizer(new \ApiBundle\Normalizer\ResourceValidationExceptionNormalizer(array('type' => 'AppBundle\\Exception\\ResourceValidationException')));
$instance->addNormalizer(new \ApiBundle\Normalizer\PersonalizedExceptionNormalizer(array('type' => 'AppBundle\\Exception\\PersonalizedException')));

return $instance;
