<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api.xliffconverter' shared service.

include_once $this->targetDirs[3].'/src/ApiBundle/Service/XliffConverter.php';

return $this->services['api.xliffconverter'] = new \ApiBundle\Service\XliffConverter($this->targetDirs[3]);
